/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//PORT REGISTERS
	 volatile unsigned int *GPIOA_MODER = (unsigned int*) (0x40020000 + 0x00);
	 volatile unsigned int *GPIOA_ODR = (unsigned int*) (0x40020000 + 0x14);
	 volatile unsigned int *GPIOC_MODER =(unsigned int*) (0x40020000 + 0x0800 + 0x00);
	 volatile unsigned int *GPIOC_IDR = (unsigned int*) (0x40020000 + 0x0800 + 0x10);
	 //CLOCK REGISTERS
	 volatile unsigned int *RCC_AHB1ENR = (unsigned int*) (0x40023800 + 0x30);
	 //VARIABLES
	 int i;
	 //ENABLE PORT CLOCK:
	 // this ensure that the peripheral is enabled and connected to the AHB1 bus
	 *RCC_AHB1ENR |= 0x01U;
	 *RCC_AHB1ENR |= 0x04U;
	 //CONFIGURE PORT: set MODER[11:10] = 0x1
	 *GPIOA_MODER = *GPIOA_MODER | 0x400;
	 // the following line is redundant but is inserted to clear the idea
	 *GPIOC_MODER = *GPIOC_MODER | 0X0000000;
	 // Application code (Infinite loop)
	 while (1)
	 {
	 // Add your code here.
	 if((*GPIOC_IDR & 0X2000) == 0X2000){
		 *GPIOA_ODR &= 0xffdf;
	 }else{
		 *GPIOA_ODR |= 0x20;
	 }
	 //*GPIOA_ODR = *GPIOA_ODR ^ ((*GPIOC_IDR & 0x2000) >> 8);
	 //*GPIOA_ODR = *GPIOA_ODR ^ 0x20;
	 /*for (i=0; i<MYWAIT; i++)
	 {
	 }*/
	 }

}
